import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import profileRouter from "./profile";
import notesRouter from "./notes";
import flashcardsRouter from "./flashcards";
import quizzesRouter from "./quizzes";
import studyPlansRouter from "./study-plans";
import documentsRouter from "./documents";
import progressRouter from "./progress";
import examTypesRouter from "./exam-types";
import openaiChatRouter from "./openai-chat";
import premiumRouter from "./premium";
import adminRouter from "./admin";
import languageRouter from "./language";
import examPlansRouter from "./exam-plans";
import focusRouter from "./focus";
import assistantRouter from "./assistant";
import coursesRouter from "./courses";
import examCalendarRouter from "./exam-calendar";
import pushNotificationsRouter from "./push-notifications";
const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(profileRouter);
router.use(notesRouter);
router.use(flashcardsRouter);
router.use(quizzesRouter);
router.use(studyPlansRouter);
router.use(documentsRouter);
router.use(progressRouter);
router.use(examTypesRouter);
router.use(openaiChatRouter);
router.use(premiumRouter);
router.use(adminRouter);
router.use(languageRouter);
router.use(examPlansRouter);
router.use(focusRouter);
router.use(assistantRouter);
router.use(coursesRouter);
router.use(examCalendarRouter);
router.use(pushNotificationsRouter);

export default router;
