// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/AtomicWorkspaceShowdown-8z24hx/index.tsx": () => import("../components/mockups/templates/AtomicWorkspaceShowdown-8z24hx/index.tsx"),
  "./components/mockups/templates/TangerineSpotlightPortrait-hxlgaQ/index.tsx": () => import("../components/mockups/templates/TangerineSpotlightPortrait-hxlgaQ/index.tsx")
};
